<? php
echo '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"';
echo '"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">';
echo '<html xmlns="http://www.w3.org/1999/xhtml">';
echo '<head>';
echo '<title>Music Viewer</title>';
echo '<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />';
echo '<link href="viewer.css" type="text/css" rel="stylesheet" />';
echo '</head>';
echo '<body>';
echo '<div id="header">';
echo '';
echo '<h1>190M Music Playlist Viewer</h1>';
echo '<h2>Search Through Your Playlists and Music</h2>';
echo '</div>';
echo '';
echo '';
echo '<div id="listarea">';
echo '<ul id="musiclist">';
echo '<li class="mp3item">';
echo '<a href="songs/Be More.mp3">Be More.mp3</a>';
echo '(5438375 b)';
echo '</li>';
echo '';
echo '<li class="mp3item">';
echo '<a href="songs/Drift Away.mp3">Drift Away.mp3</a>';
echo '(5724612 b)';
echo '</li>';
echo '';
echo '<li class="mp3item">';
echo '<a href="songs/Hello.mp3">Hello.mp3</a>';
echo '';
echo '(1871110 b)';
echo '</li>';
echo '';
echo '<li class="mp3item">';
echo '<a href="songs/Panda Sneeze.mp3">Panda Sneeze.mp3</a>';
echo '(58 b)';
echo '</li>';
echo '';
echo '<li class="playlistitem">';
echo '<a href="music.php?playlist=mypicks.txt">mypicks.txt</a>';
echo '</li>';
echo '';
echo '<li class="playlistitem">';
echo '<a href="music.php?playlist=playlist.txt">playlist.txt</a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</body>';
echo '</html>';
echo '';
?>